### ISSUE TITLE
Crash：当设置为2张图片时，向左滑动，会导致数组越界

### ISSUE THREAD

**Issue by kylesaid** [zhaiyuhao/YHImageCarousel#5]
自己有过一些尝试，并不能有效解决该crash；
删除plist，只保留2项后，run后向左滑动，会导致崩溃；

对于以下注释，没有看明白，如果能方便帮忙解释下最好不过。
// 这里使用 _currentPageIndex - 1 - 2 是因为 此时 _currentPageIndex 还未更新为最新的，_currentPageIndex - 1 为最新的位置，之前的第二个位置添加

提供错误信息以供参考：
在carouselView:cellForPageAtIndex:方法中打印出来的当时index：
YHImageCarousel[13173:261351] -1
错误信息：
2017-03-23 16:36:27.643 YHImageCarousel[13173:261351] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000101e0bd4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010186d21e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000101d3d2eb -[__NSArrayM objectAtIndex:] + 203
	3   YHImageCarousel                     0x000000010128c11a -[ViewController carouselView:cellForPageAtIndex:] + 394
	4   YHImageCarousel                     0x000000010128f6ba -[ImageCarouselView scrollViewDidScroll:] + 1322
	5   UIKit                               0x0000000102a2db0d -[UIScrollView(UIScrollViewInternal) _notifyDidScroll] + 69
	6   UIKit                               0x0000000112ad0fae -[UIScrollViewAccessibility _notifyDidScroll] + 39
	7   UIKit                               0x0000000102a180f1 -[UIScrollView setContentOffset:] + 478
	8   UIKit                               0x0000000102a2807c -[UIScrollView _smoothScrollWithUpdateTime:] + 3141
	9   QuartzCore                          0x000000010793b895 _ZN2CA7Display15DisplayLinkItem8dispatchEy + 57
	10  QuartzCore                          0x000000010793b755 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 449
	11  CoreFoundation                      0x0000000101d9ddb4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	12  CoreFoundation                      0x0000000101d9da43 __CFRunLoopDoTimer + 1075
	13  CoreFoundation                      0x0000000101d9d5ca __CFRunLoopDoTimers + 250
	14  CoreFoundation                      0x0000000101d952f1 __CFRunLoopRun + 2065
	15  CoreFoundation                      0x0000000101d94884 CFRunLoopRunSpecific + 420
	16  GraphicsServices                    0x000000010723ea6f GSEventRunModal + 161
	17  UIKit                               0x0000000102942c68 UIApplicationMain + 159
	18  YHImageCarousel                     0x00000001012905ef main + 111
	19  libdyld.dylib                       0x000000010538068d start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by JKjiangnan** [comment]
- (CarouselCell *)carouselView:(ImageCarouselView *)carouselView cellForPageAtIndex:(NSUInteger)index {
    CarouselCellImageView *cell = [[CarouselCellImageView alloc] initWithFrame:CGRectMake(0, 0, self.pageWidth - 4, self.pageHeight)];
    if (index < self.cellInfoArray.count) {
        CarouselCellInfo *cellInfo = self.cellInfoArray[index];
        cell.imageView.image = [UIImage imageNamed:[NSString stringWithFormat:@"%@", cellInfo.imageName]];
        cell.showTime = cellInfo.showTime;
    }

    return cell;
}

**Comment by JKjiangnan** [comment]
- (CarouselCell *)carouselView:(ImageCarouselView *)carouselView cellForPageAtIndex:(NSUInteger)index {
    CarouselCellImageView *cell = [[CarouselCellImageView alloc] initWithFrame:CGRectMake(0, 0, self.pageWidth - 4, self.pageHeight)];
    if (index < self.cellInfoArray.count) {
        CarouselCellInfo *cellInfo = self.cellInfoArray[index];
        cell.imageView.image = [UIImage imageNamed:[NSString stringWithFormat:@"%@", cellInfo.imageName]];
        cell.showTime = cellInfo.showTime;
    }

    return cell;
}

**Comment by JKjiangnan** [comment]
cell 方法取值时候做判断

修改之后不崩了， 但还有bug，手指拖动向右滑几个之后，会有空白图片

**Comment by JKjiangnan** [comment]
找到原因：
ImageCarouselView.m文件，scrollViewDidScroll 方法中
           
 // 这里使用 _currentPageIndex - 1 - 2 是因为 此时 _currentPageIndex 还未更新为最新的，_currentPageIndex - 1 为最新的位置，之前的第二个位置添加
CarouselCell *cell = [self.dataSource carouselView:self cellForPageAtIndex:(_pageCount + (_currentPageIndex - 1 - 2)) % _pageCount]
计算cellForPageAtIndex： index的时候得到了-1 的值 导致数组越界

修改：
            // 这里使用 _currentPageIndex - 1 - 2 是因为 此时 _currentPageIndex 还未更新为最新的，_currentPageIndex - 1 为最新的位置，之前的第二个位置添加
            NSInteger index = (_pageCount + (_currentPageIndex - 1 - 2)) % _pageCount;
            index = labs(index);//[此处取绝对值]
            CarouselCell *cell = [self.dataSource carouselView:self cellForPageAtIndex:index];

**Comment by kylesaid** [comment]
Thx
